############################################################
# TODO need to share UTS namespace as we need the hostname #
# TODO load all kernel modules                             #
############################################################
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    k8s-app: kube-proxy
  name: lxc-kube-proxy
  namespace: kube-system
spec:
  selector:
    matchLabels:
      k8s-app: kube-proxy
  updateStrategy:
    type: OnDelete
  template:
    metadata:
      labels:
        k8s-app: kube-proxy
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
    spec:
      priorityClassName: system-node-critical
      containers:
      - name: kube-proxy
        env:
          - name: user-data
            value: |
              #cloud-config
              packages:
                - kube-proxy
                - conntrack
              write_files:
                - path: /etc/systemd/system/kube-proxy.service.d/10-proxy.conf
                  owner: root:root
                  permissions: '0600'
                  content: |
                    [Service]
                    ExecStart=
                    ExecStart=/usr/bin/kube-proxy --config=/var/lib/kube-proxy/config.conf
              runcmd:
                - "systemctl enable kube-proxy"
                - "systemctl start kube-proxy"
        image: ubuntu/16.04
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /var/lib/kube-proxy
          name: kube-proxy
        - mountPath: /run/xtables.lock
          name: xtables-lock
          readOnly: false
        - mountPath: /lib/modules
          name: lib-modules
          readOnly: true
        - mountPath: /sys
          name: sys
      hostNetwork: true
      serviceAccountName: kube-proxy
      volumes:
      - name: sys
        hostPath:
          path: /sys
      - name: kube-proxy
        configMap:
          name: kube-proxy
      - name: xtables-lock
        hostPath:
          path: /run/xtables.lock
          type: FileOrCreate
      - name: lib-modules
        hostPath:
          path: /lib/modules
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - operator: Exists
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-proxy
  namespace: kube-system
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: system:kube-proxy
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
subjects:
  - kind: ServiceAccount
    name: kube-proxy
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: system:node-proxier
  apiGroup: rbac.authorization.k8s.io
